### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by DevChaudhary78** [Kirbitz/neo-themes.nvim#7]
### Description

I wanted to have a plugin similar to `Mason`, using which we can manage many themes that could be found online and could be configured with just a few keystrokes. Surprisingly I didn't find any solution and decided to create my own, and later stumbled upon this repository, so I was just curious are you still working on this project?

### Additional Information

You can check out Mason here: [Mason](https://github.com/williamboman/mason.nvim)

**Comment by Kirbitz** [comment]
Yeah, this project is still alive, just haven't really been working on it due to starting a new job and wanting to just relax after work.  I am thinking about getting back to this sometime soon just don't really know when yet.  Funny enough I was in your spot when I thought of this project after graduating last year and used Mason and Packer as heavy inspiration.

Something worth noting is that there was a bug that I ran into when developing where colorscheme does not reset when changing themes.  Now this isn't an issue when reloading nvim after a theme switch, but obviously it still sucks as a bug.

**Comment by DevChaudhary78** [comment]
Great to know this, thank you so much @Kirbitz. I would try to use this plugin for a day or two, so I could help you with maybe documentation or development. I just started my Co-op after my 3rd Semester and I am getting a bit of time to work on this fun stuff, and joyed that I was not alone who is looking for a Plugin Manager for Themes haha.

Right now I am closing this issue.
